version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: pi
      POSTGRES_PASSWORD: pi
      POSTGRES_DB: pi
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
